replicaCount: 2
image:
  repository: securebankingopsacr.azurecr.io/accounts
  tag: latest
service:
  type: NodePort
  port: 5001
  targetPort: 5001
  nodePort: 31001
resources: {}
ingress:
  enabled: false
  annotations: {}
  hosts: []
  tls: []
