replicaCount: 2
image:
  repository: securebankingopsacr.azurecr.io/payments
  tag: latest
  pullSecrets: 
    - name: acr-secret
service:
  type: NodePort
  port: 5002
  targetPort: 5002
  nodePort: 31002 
resources: {}
ingress:
  enabled: false
  annotations: {}
  hosts: []
  tls: []
