replicaCount: 2
image:
  repository: securebankingopsacr.azurecr.io/auth-service
  tag: latest
  pullSecrets: 
    - name: acr-secret
service:
  type: NodePort
  port: 5000
  targetPort: 5000
  nodePort: 31000
resources: {}
ingress:
  enabled: false
  annotations: {}
  hosts: []
  tls: []
