image:
  repository: securebankingopsacr.azurecr.io/frontend
  tag: proxy
  pullSecrets: 
    - name: acr-secret

replicaCount: 1

service:
  type: NodePort
  port: 80
  targetPort: 80
  nodePort: 30080

ingress:
  enabled: true
  host: frontend.local

env:
  REACT_APP_AUTH_URL: "http://auth-service-auth-service:5000"
  REACT_APP_ACCOUNTS_URL: "http://accounts-accounts:5001"
  REACT_APP_PAYMENTS_URL: "http://payments-payments:5002"